spring.application.name=chatactivity
# H2 Database configuration
#spring.datasource.url=jdbc:h2:mem:activiti;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=password
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#spring.h2.console.enabled=true

#MSQL Configuration #&nullCatalogMeansCurrent=true
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://localhost:3306/activiti?autoReconnect=true&nullCatalogMeansCurrent=true
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=user
spring.datasource.password=shova
spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQL5Dialect
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

# Activiti Engine configuration
spring.activiti.database-schema-update=true
spring.activiti.enabled=true
#To create history table, set the following property.
spring.activiti.dbHistoryUsed=true 
#To enable history data, it is necessary to set the following properties.
#audit or full
spring.activiti.history-level=full
spring.activiti.async-executor=true
spring.activiti.check-process-definitions=true